const poemData = [
    { text: "陈元方", py: "chén yuán fāng", zh: "陈纪，字元方，陈寔的长子，魏晋时期名士。", en: "Chen Yuanfang (Chen Ji)." },
    { text: "年", py: "nián", zh: "年龄，岁数。", en: "At the age of." },
    { text: "十一", py: "shí yī", zh: "十一。", en: "eleven." },
    { text: "岁", py: "suì", zh: "岁。", en: "years old," },
    { text: "时", py: "shí", zh: "……的时候。", en: "when" },
    { text: "，", punc: true },
    { text: "候", py: "hòu", zh: "拜访，问候。", en: "he went to visit", exam: true },
    { text: "袁公", py: "yuán gōng", zh: "袁公，指袁绍或袁滂，此处代指长辈。", en: "Lord Yuan." },
    { text: "。", punc: true },
    { text: "袁公", py: "yuán gōng", zh: "袁公。", en: "Lord Yuan" },
    { text: "问", py: "wèn", zh: "问。", en: "asked" },
    { text: "曰", py: "yuē", zh: "说。", en: "saying" },
    { text: "：“", punc: true },
    { text: "贤家君", py: "xián jiā jūn", zh: "谦词，对他人父亲的尊称。", en: "Your respected father", exam: true },
    { text: "在", py: "zài", zh: "在，任职。", en: "was at" },
    { text: "太丘", py: "tài qiū", zh: "太丘县，当时陈元方的父亲陈寔在此任县令。", en: "Taiqiu," },
    { text: "，", punc: true },
    { text: "远近", py: "yuǎn jìn", zh: "远近的人，到处。", en: "people far and wide" },
    { text: "称", py: "chēng", zh: "称赞，赞扬。", en: "praised", exam: true },
    { text: "之", py: "zhī", zh: "代词，代指他（你父亲）。", en: "him." },
    { text: "，", punc: true },
    { text: "何所", py: "hé suǒ", zh: "疑问代词短语，做了什么、有什么。", en: "What kind of", exam: true },
    { text: "履行", py: "lǚ xíng", zh: "实践，指操行、治政措施。", en: "deeds or administration did he practice?", exam: true },
    { text: "？”", punc: true },
    { text: "元方", py: "yuán fāng", zh: "元方。", en: "Yuanfang" },
    { text: "曰", py: "yuē", zh: "说。", en: "replied" },
    { text: "：“", punc: true },
    { text: "老父", py: "lǎo fù", zh: "谦词，对人称呼自己的父亲。", en: "My father", exam: true },
    { text: "在", py: "zài", zh: "在。", en: "at" },
    { text: "太丘", py: "tài qiū", zh: "太丘。", en: "Taiqiu" },
    { text: "，", punc: true },
    { text: "强者", py: "qiáng zhě", zh: "豪强，有势力的人。", en: "the powerful ones" },
    { text: "绥之", py: "suí zhī", zh: "安抚他们。“绥”，安抚、平息。", en: "he pacified them" },
    { text: "以德", py: "yǐ dé", zh: "介词短语后置，用道德。“以”，用。", en: "with virtue,", exam: true },
    { text: "，", punc: true },
    { text: "弱者", py: "ruò zhě", zh: "弱小者，贫苦百姓。", en: "the weak ones" },
    { text: "抚之", py: "fǔ zhī", zh: "抚慰他们。“抚”，体恤、优待。", en: "he comforted them" },
    { text: "以仁", py: "yǐ rén", zh: "用仁爱。", en: "with benevolence;" },
    { text: "，", punc: true },
    { text: "恣", py: "zì", zh: "听任，顺从。", en: "allowing them to do", exam: true },
    { text: "其", py: "qí", zh: "他们（各自）。", en: "what" },
    { text: "所安", py: "suǒ ān", zh: "感到安适的事。", en: "made them feel at ease," },
    { text: "，", punc: true },
    { text: "久", py: "jiǔ", zh: "时间长了。", en: "and over time," },
    { text: "而", py: "ér", zh: "表顺承，就。", en: "they" },
    { text: "益", py: "yì", zh: "更加。", en: "respected him all the more.", exam: true },
    { text: "敬", py: "jìng", zh: "敬佩，爱戴。", en: "respected" },
    { text: "。”", punc: true },
    { text: "袁公", py: "yuán gōng", zh: "袁公。", en: "Lord Yuan" },
    { text: "曰", py: "yuē", zh: "说。", en: "said" },
    { text: "：“", punc: true },
    { text: "孤", py: "gū", zh: "古代王侯或官员的自称，我。", en: "I,", exam: true },
    { text: "往者", py: "wǎng zhě", zh: "过去，从前。", en: "in the past," },
    { text: "尝", py: "cháng", zh: "副词，曾经。", en: "once" },
    { text: "为", py: "wéi", zh: "动词，担任。", en: "served as" },
    { text: "邺令", py: "yè lìng", zh: "邺县县令。", en: "the Magistrate of Ye," },
    { text: "，", punc: true },
    { text: "正", py: "zhèng", zh: "恰好，也正是。", en: "and exactly" },
    { text: "行", py: "xíng", zh: "推行，做。", en: "practiced" },
    { text: "此事", py: "cǐ shì", zh: "这些政令。", en: "this matter." },
    { text: "。", punc: true },
    { text: "不知", py: "bù zhī", zh: "不知道。", en: "I wonder if" },
    { text: "卿", py: "qīng", zh: "古代长辈对晚辈的爱称，你。", en: "your", exam: true },
    { text: "家君", py: "jiā jūn", zh: "你父亲。", en: "respected father" },
    { text: "法", py: "fǎ", zh: "动词，效法、向……学习。", en: "imitated", exam: true },
    { text: "孤", py: "gū", zh: "我。", en: "me," },
    { text: "，", punc: true },
    { text: "孤", py: "gū", zh: "我。", en: "or I" },
    { text: "法", py: "fǎ", zh: "效法。", en: "imitated" },
    { text: "卿父", py: "qīng fù", zh: "你父亲。", en: "your father?" },
    { text: "？”", punc: true },
    { text: "元方", py: "yuán fāng", zh: "元方。", en: "Yuanfang" },
    { text: "曰", py: "yuē", zh: "说。", en: "said" },
    { text: "：“", punc: true },
    { text: "周公", py: "zhōu gōng", zh: "西周初年的圣人周公旦。", en: "The Duke of Zhou" },
    { text: "、", punc: true },
    { text: "孔子", py: "kǒng zǐ", zh: "儒家创始人孔子。", en: "and Confucius," },
    { text: "，", punc: true },
    { text: "异世", py: "yì shì", zh: "不同的时代。", en: "born in different eras," },
    { text: "而", py: "ér", zh: "连词，表顺承。", en: "yet" },
    { text: "出", py: "chū", zh: "降生，出现。", en: "emerged." },
    { text: "，", punc: true },
    { text: "周旋", py: "zhōu xuán", zh: "行事，应酬交往，指日常言行。", en: "Their conducts", exam: true },
    { text: "动静", py: "dòng jìng", zh: "举止，一举一动。", en: "and principles" },
    { text: "，", punc: true },
    { text: "万里", py: "wàn lǐ", zh: "形容地域遥远或空间跨度大。", en: "were miles apart in space," },
    { text: "如一", py: "rú yī", zh: "完全一致。", en: "yet exactly the same." },
    { text: "。", punc: true },
    { text: "周公", py: "zhōu gōng", zh: "周公。", en: "The Duke of Zhou" },
    { text: "不师", py: "bù shī", zh: "不拜……为师，不效法。“师”，名词作动词。", en: "did not learn from", exam: true },
    { text: "孔子", py: "kǒng zǐ", zh: "孔子。", en: "Confucius," },
    { text: "，", punc: true },
    { text: "孔子", py: "kǒng zǐ", zh: "孔子。", en: "and Confucius" },
    { text: "亦", py: "yì", zh: "也。", en: "also" },
    { text: "不师", py: "bù shī", zh: "不效法。", en: "did not learn from" },
    { text: "周公", py: "zhōu gōng", zh: "周公。", en: "the Duke of Zhou." },
    { text: "。”", punc: true }
];
